export const SCENARIOS = [
  {
    id: 1, module: 'Primul Salariu', moduleIcon: '💸',
    principle: 'Plateste-te pe tine primul — Separa economiile in momentul in care primesti venitul, nu la final. Ce ramane dupa cheltuieli e de obicei zero.',
    situation: 'Tocmai ai primit primul salariu: 3.500 RON net. E vineri seara si ai notificarea in telefon.',
    character: 'Tu, 22 ani, primul job',
    choices: [
      { text: 'Pun 20% (700 RON) in economii, restul pentru cheltuieli', emoji: '🏦', tag: 'Regula 80/20', score: 90, color: '#00FF87', consequence: 'Excelent! Ai aplicat regula 80/20. Peste 12 luni vei avea 8.400 RON economisiti — un fond de urgenta solid.', projection: [700,1400,2100,2800,3500,4200,4900,5600] },
      { text: 'Cheltuiesc tot — merit o vacanta si niste haine noi', emoji: '🛍️', tag: 'YOLO', score: -20, color: '#FF4D4D', consequence: 'Ai simtit bine in saptamana aia. Dar la luna mai esti cu 0 in cont si orice urgenta te prinde nepregatit.', projection: [3500,0,0,0,0,0,0,0] },
      { text: 'Pun totul in economii, traiesc la minimum', emoji: '🔒', tag: 'Ultra-econom', score: 60, color: '#FFB800', consequence: "Ai economii mari, dar epuizarea te va face sa 'explodezi' si sa cheltuiesti impulsiv. Echilibrul e cheia.", projection: [3500,7000,10500,10500,7000,10500,14000,17500] },
      { text: 'Investesc 500 RON in ETF-uri, 700 RON economii, restul cheltuieli', emoji: '📈', tag: 'Strategie mixta', score: 100, color: '#00C6FF', consequence: 'Perfect! Economisesti, investesti si traiesti decent. Banii din ETF-uri cresc in medie cu 8-10% pe an.', projection: [1200,2450,3750,5100,6500,8000,9600,11300] },
    ],
  },
  {
    id: 2, module: 'Fondul de Urgenta', moduleIcon: '🚨',
    principle: 'Fondul de urgenta = liniste financiara — 3-6 salarii puse deoparte inseamna ca orice surpriza (masina stricata, job pierdut) nu devine o catastrofa.',
    situation: 'Masina ta s-a stricat. Reparatia costa 2.000 RON. Nu ai fond de urgenta. Ce faci?',
    character: 'Tu, 23 ani, 6 luni de job',
    choices: [
      { text: 'Iau credit rapid online (dobanda 35% pe an)', emoji: '💳', tag: 'Credit rapid', score: -30, color: '#FF4D4D', consequence: 'Ai rezolvat urgent, dar 2.000 RON devin 2.700 RON in 12 luni. Dobanzile iti mananca economiile viitoare.', projection: [0,-200,-400,-500,-400,-200,0,200] },
      { text: 'Cer bani imprumut de la parinti', emoji: '👨‍👩‍👦', tag: 'Familia ajuta', score: 10, color: '#FFB800', consequence: 'Ai rezolvat fara dobanda, dar dependenta de familie nu e sustenabila. Construieste-ti fondul!', projection: [0,0,200,400,600,800,1200,2000] },
      { text: 'Vand ceva (laptop vechi, haine) si acopăr partial', emoji: '📦', tag: 'Lichidez active', score: 30, color: '#00FF87', consequence: 'Ingenios! Lectia e clara: un fond de urgenta de 3 salarii te-ar fi salvat fara stres.', projection: [500,800,1100,1400,1700,2000,2300,2600] },
      { text: 'Iau bani din fondul de urgenta (eram pregatit!)', emoji: '🛡️', tag: 'Eram pregatit!', score: 100, color: '#00C6FF', consequence: 'Exact pentru asta exista fondul de urgenta! Nicio dobanda, niciun stres. Acum recompletezi treptat.', projection: [5000,3000,3500,4000,4500,5000,5500,6000] },
    ],
  },
  {
    id: 3, module: 'Chiria', moduleIcon: '🏠',
    principle: 'Regula 30% — Chiria nu ar trebui sa depaseasca 30% din venitul net. Peste acest prag, orice schimbare mica iti dezechilibreaza intreg bugetul.',
    situation: 'Vrei sa te muti singur. Ai 3 optiuni in Bucuresti. Salariul tau: 4.000 RON.',
    character: 'Tu, 24 ani, job stabil',
    choices: [
      { text: 'Garsoniera centrala: 2.200 RON/luna (55% din salariu)', emoji: '🌆', tag: 'Locatie premium', score: -20, color: '#FF4D4D', consequence: 'Locatie buna, dar ramai cu 1.800 RON pentru tot restul. Orice schimbare la job te pune in pericol.', projection: [0,-100,-200,-400,-600,-500,-300,-100] },
      { text: 'Apartament periferie: 1.200 RON/luna (30% din salariu)', emoji: '🏘️', tag: 'Echilibru', score: 90, color: '#00FF87', consequence: 'Regula de aur: chiria sub 30% din venit. Ai 2.800 RON ramasi pentru trai decent si economii.', projection: [0,600,1200,1800,2400,3000,3600,4200] },
      { text: 'Colegi de apartament: 700 RON/luna (17% din salariu)', emoji: '👥', tag: 'Shared living', score: 80, color: '#00C6FF', consequence: 'Economisesti masiv! Cu 1.000+ RON/luna economisit, in 2 ani ai avans pentru credit ipotecar.', projection: [0,1000,2000,3000,4000,5000,6000,7000] },
      { text: 'Raman la parinti si economisesc chiria', emoji: '🏡', tag: 'Strategic', score: 70, color: '#FFB800', consequence: 'Daca situatia permite, e cea mai rapida cale spre independenta financiara reala. Fara judecati!', projection: [0,1500,3000,4500,6000,7500,9000,10500] },
    ],
  },
  {
    id: 4, module: 'Prima Investitie', moduleIcon: '📊',
    principle: 'Dobanda compusa — al 8-lea miracol al lumii — Banii investiti timpuriu cresc exponential. 1.000 RON investiti la 25 ani valorează de 3x mai mult decat acelasi 1.000 RON investit la 35 ani.',
    situation: 'Ai economisit 5.000 RON. Prietenul tau iti zice ca trebuie sa ii pui la treaba. Ce faci?',
    character: 'Tu, 25 ani, economii de baza',
    choices: [
      { text: 'Bag tot pe crypto — prietenul a castigat 300%', emoji: '🎰', tag: 'High risk', score: -40, color: '#FF4D4D', consequence: '80% din retail investitori pierd bani pe crypto. Prietenul tau a avut noroc. Tu poate nu.', projection: [5000,9000,3000,800,2000,5000,2000,6000] },
      { text: 'ETF global (S&P500 sau MSCI World) pe termen lung', emoji: '🌍', tag: 'Investitie solida', score: 100, color: '#00FF87', consequence: 'Cel mai bun start! Randament mediu 8-10%/an. 5.000 RON devin ~10.000 RON in 8-10 ani fara sa faci nimic.', projection: [5000,5400,5832,6298,6802,7346,7934,8569] },
      { text: 'Depozit bancar — sigur si fara risc', emoji: '🏛️', tag: 'Super sigur', score: 40, color: '#FFB800', consequence: 'Sigur, dar cu dobanda de 5-6% abia bati inflatia. Bun pentru fondul de urgenta, nu pentru investitii.', projection: [5000,5250,5512,5787,6077,6381,6700,7035] },
      { text: 'Curs/certificare care sa imi creasca salariul', emoji: '🎓', tag: 'Investitie in sine', score: 95, color: '#00C6FF', consequence: 'Cea mai buna investitie esti tu! Un curs bun poate adauga 500-1000 RON/luna la salariu.', projection: [5000,5500,6500,8000,9500,11000,13000,15000] },
    ],
  },
  {
    id: 5, module: 'Datorii si Credit', moduleIcon: '💳',
    principle: 'Datoria buna vs. datoria rea — Creditul cu dobanda 0% folosit disciplinat e un instrument. Creditul rapid cu dobanda 35% e o capcana. Diferenta o face costul real al banilor.',
    situation: 'Vrei un laptop nou de 4.000 RON pentru freelancing. Nu ai economiile necesare acum.',
    character: 'Tu, 24 ani, freelancer part-time',
    choices: [
      { text: 'Card de credit cu dobanda 0% in 12 rate egale', emoji: '💳', tag: 'Credit inteligent', score: 80, color: '#00FF87', consequence: 'Daca platesti toate ratele la timp, nu platesti dobanda. Instrumentul corect, folosit corect.', projection: [0,-333,-666,-999,-666,-333,0,500] },
      { text: 'Credit rapid online cu dobanda 35%/an', emoji: '⚡', tag: 'Credit scump', score: -40, color: '#FF4D4D', consequence: '4.000 RON devin 5.400 RON in 12 luni. Platesti laptopul de 1,35 ori. Evita credite cu dobanzi mari!', projection: [0,-450,-900,-1200,-900,-600,-200,0] },
      { text: 'Economisesc 3 luni si il cumpar cash', emoji: '⏳', tag: 'Rabdare', score: 90, color: '#00C6FF', consequence: 'Nicio dobanda, niciun stres. 3 luni de asteptare vs. 12 luni de rate. Matematic castiga.', projection: [0,1333,2666,4000,4500,5000,5500,6000] },
      { text: 'Cumpar refurbished certificat de 1.800 RON', emoji: '♻️', tag: 'Smart buy', score: 85, color: '#FFB800', consequence: 'Inteligent! Un refurbished certificat face acelasi job pentru freelancing la jumatate din pret.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
    ],
  },
  {
    id: 6, module: 'Pensie Privata', moduleIcon: '🧓',
    principle: 'Timpul e cel mai valoros activ financiar — 100 RON/luna de la 25 ani = ~180.000 RON la pensie. Acelasi 100 RON/luna de la 40 ani = ~55.000 RON. Incepi azi, nu maine.',
    situation: 'HR-ul te intreaba daca vrei sa contribui voluntar la Pilonul 3. Ai 26 de ani.',
    character: 'Tu, 26 ani, angajat full-time',
    choices: [
      { text: 'Nu, am 26 de ani — e mult prea devreme pentru pensie', emoji: '🙅', tag: 'Aman', score: -30, color: '#FF4D4D', consequence: '100 RON/luna de la 26 ani = ~180.000 RON la 65 ani (7% randament). Timpul e cel mai mare avantaj!', projection: [0,0,0,0,0,0,0,0] },
      { text: 'Da, 100 RON/luna — incerc si vad cum merge', emoji: '✅', tag: 'Start mic', score: 80, color: '#00FF87', consequence: 'Perfectul e dusmanul binelui. 100 RON acum > 0 RON perfect planificat mai tarziu.', projection: [100,214,335,462,596,738,887,1045] },
      { text: 'Da, maximul deductibil (400 EUR/an) — avantaj fiscal', emoji: '🎯', tag: 'Optimizat fiscal', score: 100, color: '#00C6FF', consequence: 'Nu doar economisesti pentru pensie, dar iti reduci impozitul cu pana la 400 EUR. Dublu castig.', projection: [200,414,642,884,1141,1415,1706,2015] },
      { text: 'Investesc singur in ETF-uri, nu vreau fonduri de pensii', emoji: '📱', tag: 'DIY investing', score: 85, color: '#FFB800', consequence: 'Valid daca esti disciplinat! ETF-urile au costuri mai mici. Pierzi insa deducerea fiscala.', projection: [200,416,648,897,1164,1451,1758,2087] },
    ],
  },
  {
    id: 7, module: 'Freelancing si Taxe', moduleIcon: '🧾',
    principle: 'Venitul brut nu este venitul tau — Ca freelancer, statul e partenerul tau silentios. Din fiecare leu castigat, pune deoparte 30-40% pentru taxe inainte de a cheltui orice.',
    situation: 'Ai castigat 5.000 RON extra pe Upwork luna asta. E prima data. Ce faci cu banii?',
    character: 'Tu, 25 ani, angajat + freelancer',
    choices: [
      { text: 'Nu declar nimic — e o suma mica, nimeni nu stie', emoji: '🙈', tag: 'Risc fiscal', score: -50, color: '#FF4D4D', consequence: 'ANAF verifica tot mai des tranzactiile online. Amenzile + penalitatile pot depasi suma castigata.', projection: [5000,3000,3000,3000,3000,3000,3000,3000] },
      { text: 'Deschid PFA si declar corect, platesc impozitele', emoji: '📋', tag: 'Conform legal', score: 90, color: '#00FF87', consequence: 'Singura varianta sustenabila. Cu PFA optimizat, platesti 10-16% efectiv. Legal si linistit.', projection: [5000,4250,4250,4500,4750,5000,5250,5500] },
      { text: 'Pun deoparte 40% pentru taxe, restul cheltuiesc', emoji: '🗂️', tag: 'Provizion taxe', score: 80, color: '#00C6FF', consequence: 'Decizie inteleapta! Multi freelanceri uita ca nu au impozit retinut la sursa.', projection: [5000,4200,4200,4400,4600,4800,5000,5200] },
      { text: 'Cheltuiesc tot acum, ma ocup de taxe mai tarziu', emoji: '🎉', tag: 'Procrastinare', score: -20, color: '#FFB800', consequence: "'Mai tarziu' devine niciodata si datoriile fiscale cresc cu penalitati.", projection: [5000,0,-500,-1000,-500,0,500,1000] },
    ],
  },
  {
    id: 8, module: 'Credit Auto', moduleIcon: '🚗',
    principle: 'Masina e o cheltuiala, nu o investitie — O masina noua pierde 20-30% din valoare in primul an. Costul real include dobanda, asigurarea, intretinerea si deprecierea.',
    situation: 'Ai nevoie de masina pentru job. Buget lunar disponibil pentru transport: 500 RON.',
    character: 'Tu, 27 ani, salariu 5.000 RON',
    choices: [
      { text: 'Masina noua pe credit 5 ani (500 RON/luna + asigurare)', emoji: '🚙', tag: 'Status symbol', score: -20, color: '#FF4D4D', consequence: 'Masina noua pierde 20-30% din valoare in primul an. Platesti 30.000 RON pentru ceva ce valoreaza 22.000 RON.', projection: [0,-500,-1000,-1500,-2000,-2500,-3000,-3500] },
      { text: 'Masina second-hand fiabila (7-10 ani), platita cash', emoji: '🔧', tag: 'Valoare reala', score: 100, color: '#00FF87', consequence: 'Cea mai buna decizie! Zero rate, zero dobanzi. Economiile de 500 RON/luna merg in investitii.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
      { text: 'Transport public + car sharing (Zipcar/Bolt Drive)', emoji: '🚌', tag: 'Zero ownership', score: 85, color: '#00C6FF', consequence: 'Daca jobul permite, economisesti 800-1200 RON/luna fata de a detine o masina.', projection: [0,800,1600,2400,3200,4000,4800,5600] },
      { text: 'Masina second-hand pe credit mic (200 RON/luna, 2 ani)', emoji: '📉', tag: 'Credit mic', score: 60, color: '#FFB800', consequence: 'Compromis rezonabil daca nu ai economii suficiente. Dobanda e mica si ai mobilitate.', projection: [0,-200,-400,-200,0,300,700,1100] },
    ],
  },
  {
    id: 9, module: 'Buget si Obiceiuri', moduleIcon: '📅',
    principle: 'Ce se masoara, se imbunatateste — Simpla urmarire a cheltuielilor le reduce in medie cu 15-20%. Nu ai nevoie de un buget perfect, ai nevoie de constiintizare.',
    situation: 'Luna asta ai depasit bugetul cu 800 RON fara sa stii exact unde s-au dus banii.',
    character: 'Tu, 26 ani, venituri regulate',
    choices: [
      { text: 'Ignor — data viitoare voi fi mai atent', emoji: '🙄', tag: 'Ignoranta', score: -20, color: '#FF4D4D', consequence: "'Data viitoare' nu vine fara un sistem. Fara tracking, acelasi lucru se va repeta luna viitoare.", projection: [0,-800,-1600,-2400,-3200,-4000,-4800,-5600] },
      { text: 'Revizuiesc extrasul de cont si identific categoriile', emoji: '🔍', tag: 'Analiza', score: 90, color: '#00FF87', consequence: 'Awareness-ul e primul pas. Cel mai probabil vei gasi: livrari, abonamente uitate, cumparaturi impulsive.', projection: [0,200,400,600,800,1000,1200,1400] },
      { text: 'Instalez o aplicatie de buget si urmaresc fiecare leu', emoji: '📱', tag: 'Sistem', score: 100, color: '#00C6FF', consequence: 'Studiile arata ca simpla urmarire a cheltuielilor le reduce cu 15-20%. Ce se masoara, se imbunatateste.', projection: [0,500,1000,1200,1400,1600,1800,2000] },
      { text: 'Tai 2 abonamente pe care oricum nu le folosesc', emoji: '✂️', tag: 'Quick win', score: 70, color: '#FFB800', consequence: 'Un castig rapid si concret! Romanii au in medie 4-6 abonamente, jumatate neutilizate.', projection: [0,300,600,900,1200,1500,1800,2100] },
    ],
  },
  {
    id: 10, module: 'Asigurari', moduleIcon: '🛡️',
    principle: 'Asigurarea cumpara liniste, nu produse — Scopul asigurarii nu e sa castigi bani, ci sa transferi un risc pe care nu ti-l permiti. Asigura ce nu poti inlocui din economii.',
    situation: 'Un agent de asigurari te suna si iti ofera un pachet complet. Cum reactionezi?',
    character: 'Tu, 28 ani, venituri si familie in plan',
    choices: [
      { text: 'Refuz tot — asigurarile sunt o risipa de bani', emoji: '❌', tag: 'Fara protectie', score: -30, color: '#FF4D4D', consequence: 'O singura spitalizare neasteptata poate costa 5.000-50.000 RON. Asigurarea transfera un risc pe care nu ti-l permiti.', projection: [0,0,0,0,-10000,-10000,-10000,-10000] },
      { text: 'Iau asigurare de sanatate privata + asigurare de viata term', emoji: '🏥', tag: 'Esentialul', score: 100, color: '#00FF87', consequence: 'Perfect! Sanatate (100-200 RON/luna) + viata term (50-100 RON/luna) sunt fundamentale la 28 ani.', projection: [0,-150,-300,-300,5000,5000,5000,5000] },
      { text: 'Iau tot ce ofera agentul — mai multa protectie, mai bine', emoji: '📦', tag: 'Supra-asigurat', score: 20, color: '#FFB800', consequence: 'Asigurarile inutile = bani aruncati. Asigurarea de viata whole life rar se justifica la 28 ani.', projection: [0,-400,-800,-800,500,500,500,500] },
      { text: 'Cer timp, fac research si compar mai multe oferte', emoji: '🔎', tag: 'Due diligence', score: 95, color: '#00C6FF', consequence: 'Inteligent! Acelasi nivel de acoperire poate diferi cu 40-60% in pret intre asiguratori.', projection: [0,-120,-240,-240,4000,4000,4000,4000] },
    ],
  },
]

export const CHALLENGES = [
  { id: 1, icon: '🍕', title: 'Zero livrari, 7 zile', desc: 'Nu comanda mancare sau bauturi 7 zile consecutive. Gatesti sau cumperi de la supermarket.', saving: '~150-300 RON', tip: 'Media unui tanar cheltuie 200-400 RON/luna pe livrari. E prima economie automata.' },
  { id: 2, icon: '✂️', title: 'Audit abonamente', desc: 'Listeaza TOATE abonamentele lunare si anuleaza cel putin unul neutilizat.', saving: '~30-150 RON/luna', tip: 'Romanii au in medie 4-6 abonamente active. Jumatate sunt subutilizate.' },
  { id: 3, icon: '💰', title: 'Regula 24 ore', desc: 'Inainte de orice cumparatura mai mare de 200 RON, astepti 24 de ore fara exceptie.', saving: '~200-800 RON', tip: '80% din cumpararaturile impulsive nu se mai fac dupa 24h de reflectie.' },
  { id: 4, icon: '📊', title: 'Tracker 30 zile', desc: 'Noteaza FIECARE cheltuiala 30 de zile intr-o aplicatie sau caiet.', saving: '~15-20% cheltuieli', tip: 'Simpla urmarire a cheltuielilor le reduce in medie cu 15-20%.' },
  { id: 5, icon: '🎓', title: '1 ora de educatie financiara', desc: 'Citeste sau asculta 1 ora de continut despre finante personale aceasta saptamana.', saving: 'Mii de RON pe termen lung', tip: "Recomandare: 'Omul cel mai bogat din Babilon' — lectura dureaza 3-4 ore." },
  { id: 6, icon: '🏦', title: 'Automatizeaza economiile', desc: 'Seteaza un transfer automat de 10% din salariu in ziua in care primesti banii.', saving: '10% din venit', tip: 'Plateste-te pe tine primul. Nu economisi ce ramane — cheltuiesti ce ramane dupa ce ai economisit.' },
  { id: 7, icon: '🔍', title: 'Calculeaza rata de economisire', desc: 'Calculeaza exact cate procente din venit net economisesti acum.', saving: 'Constiintizare', tip: 'Rata optima: 15-20% din venit net. Sub 10% e zona de risc.' },
  { id: 8, icon: '🚫', title: 'Digital detox shopping', desc: 'Goleste cosul din toate magazinele online si nu adauga nimic 5 zile.', saving: '~100-500 RON', tip: 'Elimina notificarile push de la aplicatiile de shopping pentru a reduce tentatiile permanent.' },
]
