export const SCENARIOS = [
  {
    id: 1, module: 'Primul Salariu', moduleIcon: '💸',
    principle: 'Plateste-te pe tine primul — Separa economiile in momentul in care primesti venitul, nu la final. Ce ramane dupa cheltuieli e de obicei zero.',
    situation: 'Tocmai ai primit primul salariu: 3.500 RON net. E vineri seara si ai notificarea in telefon.',
    character: 'Tu, 22 ani, primul job',
    choices: [
      { text: 'Pun 20% (700 RON) in economii, restul pentru cheltuieli', emoji: '🏦', tag: 'Regula 80/20', score: 90, color: '#00FF87', consequence: 'Excelent! Ai aplicat regula 80/20. Peste 12 luni vei avea 8.400 RON economisiti — un fond de urgenta solid.', projection: [700,1400,2100,2800,3500,4200,4900,5600] },
      { text: 'Cheltuiesc tot — merit o vacanta si niste haine noi', emoji: '🛍️', tag: 'YOLO', score: -20, color: '#FF4D4D', consequence: 'Ai simtit bine in saptamana aia. Dar la luna mai esti cu 0 in cont si orice urgenta te prinde nepregatit.', projection: [3500,0,0,0,0,0,0,0] },
      { text: 'Pun totul in economii, traiesc la minimum', emoji: '🔒', tag: 'Ultra-econom', score: 60, color: '#FFB800', consequence: "Ai economii mari, dar epuizarea te va face sa 'explodezi' si sa cheltuiesti impulsiv. Echilibrul e cheia.", projection: [3500,7000,10500,10500,7000,10500,14000,17500] },
      { text: 'Investesc 500 RON in ETF-uri, 700 RON economii, restul cheltuieli', emoji: '📈', tag: 'Strategie mixta', score: 100, color: '#00C6FF', consequence: 'Perfect! Economisesti, investesti si traiesti decent. Banii din ETF-uri cresc in medie cu 8-10% pe an.', projection: [1200,2450,3750,5100,6500,8000,9600,11300] },
    ],
  },
  {
    id: 2, module: 'Fondul de Urgenta', moduleIcon: '🚨',
    principle: 'Fondul de urgenta = liniste financiara — 3-6 salarii puse deoparte inseamna ca orice surpriza (masina stricata, job pierdut) nu devine o catastrofa.',
    situation: 'Masina ta s-a stricat. Reparatia costa 2.000 RON. Nu ai fond de urgenta. Ce faci?',
    character: 'Tu, 23 ani, 6 luni de job',
    choices: [
      { text: 'Iau credit rapid online (dobanda 35% pe an)', emoji: '💳', tag: 'Credit rapid', score: -30, color: '#FF4D4D', consequence: 'Ai rezolvat urgent, dar 2.000 RON devin 2.700 RON in 12 luni. Dobanzile iti mananca economiile viitoare.', projection: [0,-200,-400,-500,-400,-200,0,200] },
      { text: 'Cer bani imprumut de la parinti', emoji: '👨‍👩‍👦', tag: 'Familia ajuta', score: 10, color: '#FFB800', consequence: 'Ai rezolvat fara dobanda, dar dependenta de familie nu e sustenabila. Construieste-ti fondul!', projection: [0,0,200,400,600,800,1200,2000] },
      { text: 'Vand ceva (laptop vechi, haine) si acopar partial', emoji: '📦', tag: 'Lichidez active', score: 30, color: '#00FF87', consequence: 'Ingenios! Lectia e clara: un fond de urgenta de 3 salarii te-ar fi salvat fara stres.', projection: [500,800,1100,1400,1700,2000,2300,2600] },
      { text: 'Iau bani din fondul de urgenta (eram pregatit!)', emoji: '🛡️', tag: 'Eram pregatit!', score: 100, color: '#00C6FF', consequence: 'Exact pentru asta exista fondul de urgenta! Nicio dobanda, niciun stres. Acum recompletezi treptat.', projection: [5000,3000,3500,4000,4500,5000,5500,6000] },
    ],
  },
  {
    id: 3, module: 'Chiria', moduleIcon: '🏠',
    principle: 'Regula 30% — Chiria nu ar trebui sa depaseasca 30% din venitul net. Peste acest prag, orice schimbare mica iti dezechilibreaza intreg bugetul.',
    situation: 'Vrei sa te muti singur. Ai 3 optiuni in Bucuresti. Salariul tau: 4.000 RON.',
    character: 'Tu, 24 ani, job stabil',
    choices: [
      { text: 'Garsoniera centrala: 2.200 RON/luna (55% din salariu)', emoji: '🌆', tag: 'Locatie premium', score: -20, color: '#FF4D4D', consequence: 'Locatie buna, dar ramai cu 1.800 RON pentru tot restul. Orice schimbare la job te pune in pericol.', projection: [0,-100,-200,-400,-600,-500,-300,-100] },
      { text: 'Apartament periferie: 1.200 RON/luna (30% din salariu)', emoji: '🏘️', tag: 'Echilibru', score: 90, color: '#00FF87', consequence: 'Regula de aur: chiria sub 30% din venit. Ai 2.800 RON ramasi pentru trai decent si economii.', projection: [0,600,1200,1800,2400,3000,3600,4200] },
      { text: 'Colegi de apartament: 700 RON/luna (17% din salariu)', emoji: '👥', tag: 'Shared living', score: 80, color: '#00C6FF', consequence: 'Economisesti masiv! Cu 1.000+ RON/luna economisit, in 2 ani ai avans pentru credit ipotecar.', projection: [0,1000,2000,3000,4000,5000,6000,7000] },
      { text: 'Raman la parinti si economisesc chiria', emoji: '🏡', tag: 'Strategic', score: 70, color: '#FFB800', consequence: 'Daca situatia permite, e cea mai rapida cale spre independenta financiara reala. Fara judecati!', projection: [0,1500,3000,4500,6000,7500,9000,10500] },
    ],
  },
  {
    id: 4, module: 'Prima Investitie', moduleIcon: '📊',
    principle: 'Dobanda compusa — al 8-lea miracol al lumii — Banii investiti timpuriu cresc exponential. 1.000 RON investiti la 25 ani valorează de 3x mai mult decat acelasi 1.000 RON investit la 35 ani.',
    situation: 'Ai economisit 5.000 RON. Prietenul tau iti zice ca trebuie sa ii pui la treaba. Ce faci?',
    character: 'Tu, 25 ani, economii de baza',
    choices: [
      { text: 'Bag tot pe crypto — prietenul a castigat 300%', emoji: '🎰', tag: 'High risk', score: -40, color: '#FF4D4D', consequence: '80% din retail investitori pierd bani pe crypto. Prietenul tau a avut noroc. Tu poate nu.', projection: [5000,9000,3000,800,2000,5000,2000,6000] },
      { text: 'ETF global (S&P500 sau MSCI World) pe termen lung', emoji: '🌍', tag: 'Investitie solida', score: 100, color: '#00FF87', consequence: 'Cel mai bun start! Randament mediu 8-10%/an. 5.000 RON devin ~10.000 RON in 8-10 ani fara sa faci nimic.', projection: [5000,5400,5832,6298,6802,7346,7934,8569] },
      { text: 'Depozit bancar — sigur si fara risc', emoji: '🏛️', tag: 'Super sigur', score: 40, color: '#FFB800', consequence: 'Sigur, dar cu dobanda de 5-6% abia bati inflatia. Bun pentru fondul de urgenta, nu pentru investitii.', projection: [5000,5250,5512,5787,6077,6381,6700,7035] },
      { text: 'Curs/certificare care sa imi creasca salariul', emoji: '🎓', tag: 'Investitie in sine', score: 95, color: '#00C6FF', consequence: 'Cea mai buna investitie esti tu! Un curs bun poate adauga 500-1000 RON/luna la salariu.', projection: [5000,5500,6500,8000,9500,11000,13000,15000] },
    ],
  },
  {
    id: 5, module: 'Datorii si Credit', moduleIcon: '💳',
    principle: 'Datoria buna vs. datoria rea — Creditul cu dobanda 0% folosit disciplinat e un instrument. Creditul rapid cu dobanda 35% e o capcana. Diferenta o face costul real al banilor.',
    situation: 'Vrei un laptop nou de 4.000 RON pentru freelancing. Nu ai economiile necesare acum.',
    character: 'Tu, 24 ani, freelancer part-time',
    choices: [
      { text: 'Card de credit cu dobanda 0% in 12 rate egale', emoji: '💳', tag: 'Credit inteligent', score: 80, color: '#00FF87', consequence: 'Daca platesti toate ratele la timp, nu platesti dobanda. Instrumentul corect, folosit corect.', projection: [0,-333,-666,-999,-666,-333,0,500] },
      { text: 'Credit rapid online cu dobanda 35%/an', emoji: '⚡', tag: 'Credit scump', score: -40, color: '#FF4D4D', consequence: '4.000 RON devin 5.400 RON in 12 luni. Platesti laptopul de 1,35 ori. Evita credite cu dobanzi mari!', projection: [0,-450,-900,-1200,-900,-600,-200,0] },
      { text: 'Economisesc 3 luni si il cumpar cash', emoji: '⏳', tag: 'Rabdare', score: 90, color: '#00C6FF', consequence: 'Nicio dobanda, niciun stres. 3 luni de asteptare vs. 12 luni de rate. Matematic castiga.', projection: [0,1333,2666,4000,4500,5000,5500,6000] },
      { text: 'Cumpar refurbished certificat de 1.800 RON', emoji: '♻️', tag: 'Smart buy', score: 85, color: '#FFB800', consequence: 'Inteligent! Un refurbished certificat face acelasi job pentru freelancing la jumatate din pret.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
    ],
  },
  {
    id: 6, module: 'Pensie Privata', moduleIcon: '🧓',
    principle: 'Timpul e cel mai valoros activ financiar — 100 RON/luna de la 25 ani = ~180.000 RON la pensie. Acelasi 100 RON/luna de la 40 ani = ~55.000 RON. Incepi azi, nu maine.',
    situation: 'HR-ul te intreaba daca vrei sa contribui voluntar la Pilonul 3. Ai 26 de ani.',
    character: 'Tu, 26 ani, angajat full-time',
    choices: [
      { text: 'Nu, am 26 de ani — e mult prea devreme pentru pensie', emoji: '🙅', tag: 'Aman', score: -30, color: '#FF4D4D', consequence: '100 RON/luna de la 26 ani = ~180.000 RON la 65 ani (7% randament). Timpul e cel mai mare avantaj!', projection: [0,0,0,0,0,0,0,0] },
      { text: 'Da, 100 RON/luna — incerc si vad cum merge', emoji: '✅', tag: 'Start mic', score: 80, color: '#00FF87', consequence: 'Perfectul e dusmanul binelui. 100 RON acum > 0 RON perfect planificat mai tarziu.', projection: [100,214,335,462,596,738,887,1045] },
      { text: 'Da, maximul deductibil (400 EUR/an) — avantaj fiscal', emoji: '🎯', tag: 'Optimizat fiscal', score: 100, color: '#00C6FF', consequence: 'Nu doar economisesti pentru pensie, dar iti reduci impozitul cu pana la 400 EUR. Dublu castig.', projection: [200,414,642,884,1141,1415,1706,2015] },
      { text: 'Investesc singur in ETF-uri, nu vreau fonduri de pensii', emoji: '📱', tag: 'DIY investing', score: 85, color: '#FFB800', consequence: 'Valid daca esti disciplinat! ETF-urile au costuri mai mici. Pierzi insa deducerea fiscala.', projection: [200,416,648,897,1164,1451,1758,2087] },
    ],
  },
  {
    id: 7, module: 'Freelancing si Taxe', moduleIcon: '🧾',
    principle: 'Venitul brut nu este venitul tau — Ca freelancer, statul e partenerul tau silentios. Din fiecare leu castigat, pune deoparte 30-40% pentru taxe inainte de a cheltui orice.',
    situation: 'Ai castigat 5.000 RON extra pe Upwork luna asta. E prima data. Ce faci cu banii?',
    character: 'Tu, 25 ani, angajat + freelancer',
    choices: [
      { text: 'Nu declar nimic — e o suma mica, nimeni nu stie', emoji: '🙈', tag: 'Risc fiscal', score: -50, color: '#FF4D4D', consequence: 'ANAF verifica tot mai des tranzactiile online. Amenzile + penalitatile pot depasi suma castigata.', projection: [5000,3000,3000,3000,3000,3000,3000,3000] },
      { text: 'Deschid PFA si declar corect, platesc impozitele', emoji: '📋', tag: 'Conform legal', score: 90, color: '#00FF87', consequence: 'Singura varianta sustenabila. Cu PFA optimizat, platesti 10-16% efectiv. Legal si linistit.', projection: [5000,4250,4250,4500,4750,5000,5250,5500] },
      { text: 'Pun deoparte 40% pentru taxe, restul cheltuiesc', emoji: '🗂️', tag: 'Provizion taxe', score: 80, color: '#00C6FF', consequence: 'Decizie inteleapta! Multi freelanceri uita ca nu au impozit retinut la sursa.', projection: [5000,4200,4200,4400,4600,4800,5000,5200] },
      { text: 'Cheltuiesc tot acum, ma ocup de taxe mai tarziu', emoji: '🎉', tag: 'Procrastinare', score: -20, color: '#FFB800', consequence: "'Mai tarziu' devine niciodata si datoriile fiscale cresc cu penalitati.", projection: [5000,0,-500,-1000,-500,0,500,1000] },
    ],
  },
  {
    id: 8, module: 'Credit Auto', moduleIcon: '🚗',
    principle: 'Masina e o cheltuiala, nu o investitie — O masina noua pierde 20-30% din valoare in primul an. Costul real include dobanda, asigurarea, intretinerea si deprecierea.',
    situation: 'Ai nevoie de masina pentru job. Buget lunar disponibil pentru transport: 500 RON.',
    character: 'Tu, 27 ani, salariu 5.000 RON',
    choices: [
      { text: 'Masina noua pe credit 5 ani (500 RON/luna + asigurare)', emoji: '🚙', tag: 'Status symbol', score: -20, color: '#FF4D4D', consequence: 'Masina noua pierde 20-30% din valoare in primul an. Platesti 30.000 RON pentru ceva ce valoreaza 22.000 RON.', projection: [0,-500,-1000,-1500,-2000,-2500,-3000,-3500] },
      { text: 'Masina second-hand fiabila (7-10 ani), platita cash', emoji: '🔧', tag: 'Valoare reala', score: 100, color: '#00FF87', consequence: 'Cea mai buna decizie! Zero rate, zero dobanzi. Economiile de 500 RON/luna merg in investitii.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
      { text: 'Transport public + car sharing (Zipcar/Bolt Drive)', emoji: '🚌', tag: 'Zero ownership', score: 85, color: '#00C6FF', consequence: 'Daca jobul permite, economisesti 800-1200 RON/luna fata de a detine o masina.', projection: [0,800,1600,2400,3200,4000,4800,5600] },
      { text: 'Masina second-hand pe credit mic (200 RON/luna, 2 ani)', emoji: '📉', tag: 'Credit mic', score: 60, color: '#FFB800', consequence: 'Compromis rezonabil daca nu ai economii suficiente. Dobanda e mica si ai mobilitate.', projection: [0,-200,-400,-200,0,300,700,1100] },
    ],
  },
  {
    id: 9, module: 'Buget si Obiceiuri', moduleIcon: '📅',
    principle: 'Ce se masoara, se imbunatateste — Simpla urmarire a cheltuielilor le reduce in medie cu 15-20%. Nu ai nevoie de un buget perfect, ai nevoie de constiintizare.',
    situation: 'Luna asta ai depasit bugetul cu 800 RON fara sa stii exact unde s-au dus banii.',
    character: 'Tu, 26 ani, venituri regulate',
    choices: [
      { text: 'Ignor — data viitoare voi fi mai atent', emoji: '🙄', tag: 'Ignoranta', score: -20, color: '#FF4D4D', consequence: "'Data viitoare' nu vine fara un sistem. Fara tracking, acelasi lucru se va repeta luna viitoare.", projection: [0,-800,-1600,-2400,-3200,-4000,-4800,-5600] },
      { text: 'Revizuiesc extrasul de cont si identific categoriile', emoji: '🔍', tag: 'Analiza', score: 90, color: '#00FF87', consequence: 'Awareness-ul e primul pas. Cel mai probabil vei gasi: livrari, abonamente uitate, cumparaturi impulsive.', projection: [0,200,400,600,800,1000,1200,1400] },
      { text: 'Instalez o aplicatie de buget si urmaresc fiecare leu', emoji: '📱', tag: 'Sistem', score: 100, color: '#00C6FF', consequence: 'Studiile arata ca simpla urmarire a cheltuielilor le reduce cu 15-20%. Ce se masoara, se imbunatateste.', projection: [0,500,1000,1200,1400,1600,1800,2000] },
      { text: 'Tai 2 abonamente pe care oricum nu le folosesc', emoji: '✂️', tag: 'Quick win', score: 70, color: '#FFB800', consequence: 'Un castig rapid si concret! Romanii au in medie 4-6 abonamente, jumatate neutilizate.', projection: [0,300,600,900,1200,1500,1800,2100] },
    ],
  },
  {
    id: 10, module: 'Asigurari', moduleIcon: '🛡️',
    principle: 'Asigurarea cumpara liniste, nu produse — Scopul asigurarii nu e sa castigi bani, ci sa transferi un risc pe care nu ti-l permiti. Asigura ce nu poti inlocui din economii.',
    situation: 'Un agent de asigurari te suna si iti ofera un pachet complet. Cum reactionezi?',
    character: 'Tu, 28 ani, venituri si familie in plan',
    choices: [
      { text: 'Refuz tot — asigurarile sunt o risipa de bani', emoji: '❌', tag: 'Fara protectie', score: -30, color: '#FF4D4D', consequence: 'O singura spitalizare neasteptata poate costa 5.000-50.000 RON. Asigurarea transfera un risc pe care nu ti-l permiti.', projection: [0,0,0,0,-10000,-10000,-10000,-10000] },
      { text: 'Iau asigurare de sanatate privata + asigurare de viata term', emoji: '🏥', tag: 'Esentialul', score: 100, color: '#00FF87', consequence: 'Perfect! Sanatate (100-200 RON/luna) + viata term (50-100 RON/luna) sunt fundamentale la 28 ani.', projection: [0,-150,-300,-300,5000,5000,5000,5000] },
      { text: 'Iau tot ce ofera agentul — mai multa protectie, mai bine', emoji: '📦', tag: 'Supra-asigurat', score: 20, color: '#FFB800', consequence: 'Asigurarile inutile = bani aruncati. Asigurarea de viata whole life rar se justifica la 28 ani.', projection: [0,-400,-800,-800,500,500,500,500] },
      { text: 'Cer timp, fac research si compar mai multe oferte', emoji: '🔎', tag: 'Due diligence', score: 95, color: '#00C6FF', consequence: 'Inteligent! Acelasi nivel de acoperire poate diferi cu 40-60% in pret intre asiguratori.', projection: [0,-120,-240,-240,4000,4000,4000,4000] },
    ],
  },
  {
    id: 11, module: 'Sanatate & Cheltuieli Medicale', moduleIcon: '💊',
    principle: 'Sanatatea e o investitie, nu o cheltuiala — O urgenta medicala neacoperita poate costa de 10x mai mult decat o asigurare anuala. Protejeaza-ti cel mai valoros activ: corpul.',
    situation: 'Ai nevoie de o interventie stomatologica urgenta: 2.800 RON. Nu ai asigurare privata.',
    character: 'Tu, 25 ani, angajat',
    choices: [
      { text: 'Platesc din fondul de urgenta', emoji: '🛡️', tag: 'Eram pregatit', score: 100, color: '#00FF87', consequence: 'Exact pentru asta exista fondul de urgenta! Rezolvi fara stres si fara dobanzi. Recompletezi treptat.', projection: [5000,2200,2700,3200,3700,4200,4700,5200] },
      { text: 'Iau credit rapid', emoji: '⚡', tag: 'Credit scump', score: -30, color: '#FF4D4D', consequence: '2.800 RON devin 3.780 RON in 12 luni cu dobanda de 35%. Platesti interventia si jumatate extra.', projection: [0,-300,-600,-800,-600,-300,0,300] },
      { text: 'Aman pana trece durerea', emoji: '🙈', tag: 'Evitare', score: -40, color: '#FF4D4D', consequence: 'O problema stomatologica netratata se agraveaza. Costul poate creste de 3-5 ori in cateva luni.', projection: [0,0,-1000,-3000,-5000,-5000,-5000,-5000] },
      { text: 'Negociez rate cu clinica (fara dobanda)', emoji: '🤝', tag: 'Smart', score: 80, color: '#FFB800', consequence: 'Inteligent! Multe clinici ofera esalonare fara dobanda. Rezolvi problema fara sa apelezi la credite scumpe.', projection: [0,-700,-1400,-2100,-700,300,800,1300] },
    ],
  },
  {
    id: 12, module: 'Sanatate & Cheltuieli Medicale', moduleIcon: '💊',
    principle: 'Asigurarea privata completeaza, nu inlocuieste — CNAS iti ofera acoperire de baza, dar listele de asteptare pot dura luni. O asigurare privata iti cumpara timp si acces rapid la specialist.',
    situation: 'HR-ul iti ofera asigurare privata de sanatate prin angajator — 80 RON/luna din salariu. Ai deja CNAS.',
    character: 'Tu, 27 ani, angajat',
    choices: [
      { text: 'Refuz — am deja CNAS, e suficient', emoji: '❌', tag: 'Risc', score: -20, color: '#FF4D4D', consequence: 'CNAS acopera de baza, dar listele de asteptare pot dura luni. O urgenta te poate costa mult mai mult decat 80 RON/luna.', projection: [0,0,0,0,-2000,-2000,-2000,-2000] },
      { text: 'Accept — acces rapid la specialist fara liste de asteptare', emoji: '✅', tag: 'Echilibrat', score: 90, color: '#00FF87', consequence: 'Decizie buna! 80 RON/luna e putin pentru acces rapid la specialist, analize si consultatii private.', projection: [0,-80,-160,-240,1000,1000,1000,1000] },
      { text: 'Accept si imi fac si asigurare separata in plus', emoji: '📦', tag: 'Supra-asigurat', score: 20, color: '#FFB800', consequence: 'Doua asigurari similare inseamna bani aruncati. Verifica mai intai ce acopera cea de la angajator.', projection: [0,-250,-500,-750,500,500,500,500] },
      { text: 'Compar mai intai ce acopera si decid', emoji: '🔎', tag: 'Due diligence', score: 100, color: '#00C6FF', consequence: 'Perfect! Intelegi exact ce primesti inainte sa decizi. Asigurarea potrivita e cea care acopera riscurile tale reale.', projection: [0,-80,-160,-240,1200,1200,1200,1200] },
    ],
  },
  {
    id: 13, module: 'Sanatate & Cheltuieli Medicale', moduleIcon: '💊',
    principle: 'Preventia costa mai putin decat tratamentul — Analizele anuale depisteaza probleme timpuriu, cand sunt ieftine de tratat. Amanarea poate transforma o cheltuiala de 1.500 RON intr-una de 15.000 RON.',
    situation: 'Ti se recomanda analize medicale anuale si fondul pentru analize decontate este epuizat. Costul integral: 1.500 RON.',
    character: 'Tu, 26 ani',
    choices: [
      { text: 'Nu le fac — ma simt bine, e o cheltuiala inutila', emoji: '🙅', tag: 'Risc', score: -30, color: '#FF4D4D', consequence: 'Problemele depistate tarziu costa de 5-10 ori mai mult de tratat. Sanatatea e cel mai ieftin de intretinut preventiv.', projection: [0,0,0,-5000,-10000,-10000,-10000,-10000] },
      { text: 'Le fac din bugetul lunar curent', emoji: '✅', tag: 'Preventiv', score: 90, color: '#00FF87', consequence: 'Excelent! Analizele anuale sunt cea mai buna investitie in sanatatea ta pe termen lung.', projection: [0,-1500,-1500,0,500,500,500,500] },
      { text: 'Le includ in bugetul anual ca linie fixa', emoji: '📅', tag: 'Sistem', score: 100, color: '#00C6FF', consequence: 'Perfect! Planificarea cheltuielilor medicale anuale elimina surprizele si te asigura ca nu le amani niciodata.', projection: [0,-125,-250,-375,500,500,500,500] },
      { text: 'Le aman pentru cand am bani in plus', emoji: '⏳', tag: 'Procrastinare', score: -20, color: '#FFB800', consequence: "Banii in plus nu vin niciodata singuri. 'Mai tarziu' pentru sanatate poate insemna costuri mult mai mari.", projection: [0,0,0,0,-3000,-3000,-3000,-3000] },
    ],
  },
  {
    id: 14, module: 'Cuplu & Finante Comune', moduleIcon: '💑',
    principle: 'Echitate nu inseamna egalitate — A imparti cheltuielile 50/50 cand veniturile sunt diferite creeaza dezechilibru real. Impartirea proportionala cu venitul e corecta pentru ambii parteneri.',
    situation: 'Tu si partenerul aveti venituri diferite: tu 4.000 RON, el/ea 2.500 RON. Vreti sa impartiti cheltuielile comune.',
    character: 'Tu, 26 ani, in cuplu',
    choices: [
      { text: '50/50 fix — fiecare plateste jumatate', emoji: '⚖️', tag: 'Egalitate formala', score: 40, color: '#FFB800', consequence: '50/50 pare corect dar nu e echitabil. Partenerul cu venit mai mic ramane cu mai putini bani pentru cheltuieli personale.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
      { text: 'Proportional cu venitul — tu 62%, partenerul 38%', emoji: '📊', tag: 'Echitate reala', score: 100, color: '#00FF87', consequence: 'Corect si echitabil! Ambii parteneri raman cu acelasi procent din venit pentru cheltuieli personale.', projection: [0,800,1600,2400,3200,4000,4800,5600] },
      { text: 'Cel cu venitul mai mare plateste tot', emoji: '💸', tag: 'Dezechilibru', score: -10, color: '#FF4D4D', consequence: 'Creeaza dependenta financiara si dezechilibru in relatia. Ambii parteneri trebuie sa contribuie.', projection: [0,200,400,600,800,1000,1200,1400] },
      { text: 'Cont comun in care fiecare pune 30% din venit', emoji: '🏦', tag: 'Sistem comun', score: 90, color: '#00C6FF', consequence: 'Sistem inteligent! Fiecare contribuie proportional si ambii au autonomie financiara personala.', projection: [0,750,1500,2250,3000,3750,4500,5250] },
    ],
  },
  {
    id: 15, module: 'Cuplu & Finante Comune', moduleIcon: '💑',
    principle: 'Obiectivele financiare comune necesita decizii comune — Intr-un cuplu, o cheltuiala impulsiva a unuia afecteaza obiectivele amandurora. Comunicarea deschisa despre bani e fundamentul unui cuplu financiar sanatos.',
    situation: 'Partenerul tau vrea sa cumpere un TV de 3.500 RON acum. Voi economisiti pentru avansul la apartament.',
    character: 'Tu, 27 ani, in cuplu',
    choices: [
      { text: 'Cumparam — meritam si noi ceva frumos', emoji: '📺', tag: 'Impuls', score: -30, color: '#FF4D4D', consequence: '3.500 RON inseamna 2 luni de economii pentru avans. O decizie impulsiva va intarzia obiectivul comun.', projection: [0,-3500,-3500,-3000,-2500,-2000,-1500,-1000] },
      { text: 'Refuz categoric — economiile sunt sacre', emoji: '🔒', tag: 'Rigid', score: 30, color: '#FFB800', consequence: 'Corect din punct de vedere financiar dar rigid. Discuta si gasiti un compromis care sa respecte si bunastarea emotionala.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
      { text: 'Asteptam 3 luni si cumparam din bugetul de divertisment', emoji: '🤝', tag: 'Compromis echilibrat', score: 100, color: '#00FF87', consequence: 'Perfect! Mentii obiectivul principal si gasesti o solutie care respecta si dorintele partenerului.', projection: [0,500,1000,1500,500,1000,1500,2000] },
      { text: 'Cautam un TV second-hand de 1.200 RON', emoji: '♻️', tag: 'Smart buy', score: 90, color: '#00C6FF', consequence: 'Inteligent! Obtineti ce vreti la un pret de 3x mai mic. Economisiti 2.300 RON pentru avans.', projection: [0,-1200,-700,-200,300,800,1300,1800] },
    ],
  },
  {
    id: 16, module: 'Cuplu & Finante Comune', moduleIcon: '💑',
    principle: 'Banii sunt primul subiect de conflict in cuplu — Studiile arata ca divergentele financiare sunt cauza numarul 1 a separatelor. Un plan financiar comun clar previne conflictele inainte sa apara.',
    situation: 'Tu si partenerul vreti sa va stabiliti obiective financiare comune. De unde incepeti?',
    character: 'Tu, 26 ani, in cuplu',
    choices: [
      { text: 'Nu discutam — banii sunt un subiect sensibil', emoji: '🙈', tag: 'Evitare', score: -40, color: '#FF4D4D', consequence: 'Evitarea discutiilor despre bani e principala cauza a conflictelor financiare in cuplu. Transparenta e esentiala.', projection: [0,0,0,-1000,-2000,-3000,-4000,-5000] },
      { text: 'Fiecare cu banii lui, nu amestecam finantele', emoji: '🔀', tag: 'Separat total', score: 20, color: '#FFB800', consequence: 'Functioneaza pentru unii dar complica obiectivele comune (casa, vacanta, copii). Partial e mai bine decat nimic.', projection: [0,300,600,900,1200,1500,1800,2100] },
      { text: 'Stabilim 3 obiective comune si un buget lunar impreuna', emoji: '🎯', tag: 'Planificare', score: 100, color: '#00FF87', consequence: 'Cel mai sanatos sistem! Obiective clare, contributii definite si autonomie personala pastrata.', projection: [0,800,1600,2400,3200,4000,4800,5600] },
      { text: 'Deschidem cont comun doar pentru cheltuieli comune', emoji: '🏦', tag: 'Hibrid', score: 90, color: '#00C6FF', consequence: 'Sistem hibrid inteligent! Fiecare are autonomie financiara si contribuiti impreuna la cheltuielile comune.', projection: [0,700,1400,2100,2800,3500,4200,4900] },
    ],
  },
  {
    id: 17, module: 'Creditul Ipotecar', moduleIcon: '🏡',
    principle: 'Regula 30% la credit ipotecar — Rata lunara nu ar trebui sa depaseasca 30% din venitul net al familiei. Peste acest prag, orice schimbare (job pierdut, cheltuiala neprevazuta) pune in pericol locuinta.',
    situation: 'Poti accesa un credit ipotecar de 250.000 RON pe 30 ani — rata: 1.800 RON/luna (33% din venit).',
    character: 'Tu, 28 ani, salariu 5.500 RON',
    choices: [
      { text: 'Iau creditul acum — chiria e mai mare oricum', emoji: '🏠', tag: 'Grabit', score: 40, color: '#FFB800', consequence: 'Rata de 33% e peste pragul recomandat. Orice schimbare la job sau cheltuiala neprevazuta te pune in dificultate.', projection: [0,-1800,-1800,-1800,-1800,-1800,-1800,-1800] },
      { text: 'Astept sa am avans de 25% si rata sub 30% din venit', emoji: '⏳', tag: 'Prudent', score: 100, color: '#00FF87', consequence: 'Decizie inteapta! Un avans mai mare inseamna rata mai mica, dobanda totala mai mica si mai multa siguranta.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
      { text: 'Iau creditul maxim aprobat de banca', emoji: '💰', tag: 'Risc maxim', score: -30, color: '#FF4D4D', consequence: 'Banca aproba maximul pe care il poti plati teoretic, nu confortabil. Maximul bancii nu e maximul tau optim.', projection: [0,-2500,-2500,-2500,-2500,-2500,-2500,-2500] },
      { text: 'Cumpar ceva mai mic ca sa am rata de 20% din venit', emoji: '🏘️', tag: 'Echilibrat', score: 90, color: '#00C6FF', consequence: 'Excelent! Rata de 20% iti lasa spatiu pentru economii, investitii si urgente. Siguranta financiara pe termen lung.', projection: [0,300,600,900,1200,1500,1800,2100] },
    ],
  },
  {
    id: 18, module: 'Creditul Ipotecar', moduleIcon: '🏡',
    principle: 'Dobanda fixa vs. variabila — certitudine vs. risc — Dobanda variabila pare avantajoasa cand ratele sunt mici, dar poate creste dramatic. Dobanda fixa pe termen mediu iti ofera predictibilitate si liniste financiara.',
    situation: 'Ai avans de 15% pentru un apartament de 200.000 EUR. Banca iti ofera credit cu dobanda fixa 5 ani sau variabila (mai mica acum).',
    character: 'Tu, 27 ani',
    choices: [
      { text: 'Dobanda variabila — e mai mica acum', emoji: '📉', tag: 'Risc', score: -20, color: '#FF4D4D', consequence: 'Dobanda variabila poate creste semnificativ. O crestere de 2% inseamna sute de RON in plus la rata lunara.', projection: [0,-1200,-1200,-1500,-1800,-2000,-2000,-2000] },
      { text: 'Dobanda fixa 5 ani — predictibilitate', emoji: '🔒', tag: 'Prudent', score: 90, color: '#00FF87', consequence: 'Stii exact cat platesti 5 ani. Predictibilitatea iti permite sa planifici restul bugetului cu incredere.', projection: [0,-1400,-1400,-1400,-1400,-1400,-1400,-1400] },
      { text: 'Aman decizia pana cand inteleg diferenta', emoji: '📚', tag: 'Due diligence', score: 100, color: '#00C6FF', consequence: 'Perfect! O decizie de 200.000 EUR merita timp de analiza. Consulta un broker de credite independent.', projection: [0,500,500,500,-1400,-1400,-1400,-1400] },
      { text: 'Iau ce imi da banca, nu inteleg oricum', emoji: '🤷', tag: 'Pasiv', score: -40, color: '#FF4D4D', consequence: 'A semna un contract de zeci de ani fara sa il intelegi e unul din cele mai mari riscuri financiare posibile.', projection: [0,-1500,-1800,-2000,-2000,-2000,-2000,-2000] },
    ],
  },
  {
    id: 19, module: 'Creditul Ipotecar', moduleIcon: '🏡',
    principle: 'Rambursarea anticipata vs. investitia — matematica conteaza — Daca dobanda la credit e mai mica decat randamentul investitiilor (8-10%/an ETF), investitia e mai eficienta. Calculeaza intotdeauna inainte sa decizi.',
    situation: 'Ai credit ipotecar de 5 ani. Ai economisit 10.000 RON extra. Ce faci cu ei?',
    character: 'Tu, 28 ani',
    choices: [
      { text: 'Ii cheltuiesc — merit o vacanta dupa 5 ani de rate', emoji: '✈️', tag: 'Consum', score: -20, color: '#FF4D4D', consequence: 'Dupa 5 ani de disciplina financiara, o vacanta meritata e ok — dar nu din economii extra. Pune-i la treaba intai.', projection: [0,-10000,0,0,0,0,0,0] },
      { text: 'Fac rambursare anticipata partiala la credit', emoji: '🏠', tag: 'Optimizare datorie', score: 90, color: '#00FF87', consequence: 'Reducerea datoriei principale scurteaza durata creditului si reduce dobanda totala platita. Decizie solida.', projection: [0,-10000,500,1000,1500,2000,2500,3000] },
      { text: 'Ii investesc in ETF-uri — dobanda creditului e mai mica decat randamentul', emoji: '📈', tag: 'Strategie avansata', score: 100, color: '#00C6FF', consequence: 'Corect matematic! Daca dobanda creditului e 5% si ETF-urile fac 8-10%, investitia e mai profitabila pe termen lung.', projection: [10000,10800,11664,12597,13604,14692,15868,17137] },
      { text: 'Ii pun in depozit pentru siguranta', emoji: '🏛️', tag: 'Conservator', score: 50, color: '#FFB800', consequence: 'Depozitul da 5-6%, aproximativ cat dobanda creditului. Nu pierzi, dar nici nu castigi. O solutie mediocra.', projection: [10000,10500,11025,11576,12155,12763,13401,14071] },
    ],
  },
  {
    id: 20, module: 'Telefon Nou', moduleIcon: '📱',
    principle: 'Deprecierea tehnologiei e predictibila — Un telefon flagship pierde 30-40% din valoare in primul an. Modelul anterior, cumparat dupa lansarea celui nou, ofera 90% din functionalitate la 50% din pret.',
    situation: 'Telefonul tau functioneaza bine, dar a aparut un model nou cu 4.500 RON. Il vrei.',
    character: 'Tu, 24 ani',
    choices: [
      { text: 'Il cumpar acum pe credit — 12 rate fara dobanda', emoji: '💳', tag: 'Impuls controlat', score: 50, color: '#FFB800', consequence: 'Credit fara dobanda e ok, dar 4.500 RON pentru un telefon cand cel vechi functioneaza e o dorinta, nu o nevoie.', projection: [0,-375,-750,-1125,-1500,-1125,-750,-375] },
      { text: 'Astept 6 luni si il cumpar cash din economii', emoji: '⏳', tag: 'Rabdare', score: 100, color: '#00FF87', consequence: 'Dupa 6 luni pretul scade cu 20-30%. Economisesti 900-1350 RON si nu ai rate. Rabdarea se plateste.', projection: [0,500,1000,1500,2000,-2500,-1500,-500] },
      { text: 'Il cumpar acum din economii — merit', emoji: '🛍️', tag: 'Consum', score: -20, color: '#FF4D4D', consequence: '4.500 RON din economii pentru un telefon cand cel vechi functioneaza e o decizie emotionala, nu rationala.', projection: [0,-4500,-4000,-3500,-3000,-2500,-2000,-1500] },
      { text: 'Cumpar modelul anterior la jumatate de pret', emoji: '♻️', tag: 'Smart buy', score: 90, color: '#00C6FF', consequence: 'Inteligent! 90% din functionalitate la 50% din pret. Diferenta de 2.250 RON merge in investitii.', projection: [0,-2250,-1750,-1250,-750,-250,250,750] },
    ],
  },
  {
    id: 21, module: 'Telefon Nou', moduleIcon: '📱',
    principle: 'Urgentele fara fond de urgenta sunt scumpe — Cand ai nevoie de ceva urgent si nu ai bani, platesti intotdeauna mai mult prin dobanzi, decizii grabite sau presiune emotionala.',
    situation: 'Telefonul s-a stricat complet. Ai nevoie urgenta de unul. Buget disponibil: 0 RON economii.',
    character: 'Tu, 25 ani',
    choices: [
      { text: 'Credit rapid cu dobanda 35%', emoji: '⚡', tag: 'Credit scump', score: -40, color: '#FF4D4D', consequence: 'Un telefon de 2.000 RON devine 2.700 RON in 12 luni. Urgenta fara fond de urgenta costa intotdeauna mai mult.', projection: [0,-200,-400,-600,-500,-300,-100,0] },
      { text: 'Telefon refurbished certificat cu 800 RON pe card 0% dobanda', emoji: '♻️', tag: 'Smart + credit inteligent', score: 100, color: '#00FF87', consequence: 'Solutia optima! Rezolvi urgent, platesti minim, fara dobanda. Refurbished certificat = garantie si calitate.', projection: [0,-800,-533,-267,0,267,533,800] },
      { text: 'Imprumut de la familie', emoji: '👨‍👩‍👦', tag: 'Dependenta', score: 20, color: '#FFB800', consequence: 'Rezolvi fara dobanda dar creezi dependenta. Lectia reala: fondul de urgenta elimina aceste situatii complet.', projection: [0,-1500,-1000,-500,0,500,1000,1500] },
      { text: 'Telefon nou flagship pe credit 24 luni', emoji: '🚀', tag: 'Supraindatorare', score: -30, color: '#FF4D4D', consequence: 'O urgenta nu justifica o achizitie premium pe credit lung. Rezolvi nevoia minimala, nu dorinta maxima.', projection: [0,-200,-400,-600,-800,-600,-400,-200] },
    ],
  },
  {
    id: 22, module: 'Negocierea Salariului', moduleIcon: '💼',
    principle: 'O oferta externa e cel mai puternic instrument de negociere — Angajatorii reactioneaza la pierderi mai rapid decat la cereri. O oferta concreta in mana transforma o rugaminte intr-o negociere reala.',
    situation: 'Ai primit o oferta de la alta firma cu 2.000 RON mai mult. Ce faci?',
    character: 'Tu, 25 ani, 1 an in companie',
    choices: [
      { text: 'Accept imediat oferta fara sa negociez cu actualul angajator', emoji: '🏃', tag: 'Grabit', score: 40, color: '#FFB800', consequence: 'Poate fi o decizie buna, dar ai ratat oportunitatea de a negocia. Actualul angajator putea oferi mai mult pentru a te pastra.', projection: [0,2000,4000,6000,8000,10000,12000,14000] },
      { text: 'Folosesc oferta ca leverage si negociez cu actualul angajator', emoji: '🎯', tag: 'Strategic', score: 100, color: '#00FF87', consequence: 'Cea mai buna strategie! Ai putere de negociere reala. Fie obtii marirea, fie pleci cu o oferta mai buna.', projection: [0,2000,4000,6000,8000,10000,12000,14000] },
      { text: 'Refuz — ma simt loial firmei actuale', emoji: '🤝', tag: 'Loialitate costisitoare', score: -20, color: '#FF4D4D', consequence: 'Loialitatea e valoroasa dar nu trebuie sa te coste 2.000 RON/luna. In 5 ani asta inseamna 120.000 RON diferenta.', projection: [0,0,0,0,0,0,0,0] },
      { text: 'Cer marire fara sa mentionez oferta', emoji: '🙏', tag: 'Naiv', score: 30, color: '#FFB800', consequence: 'Poti obtine o marire, dar fara leverage concret sansele sunt mai mici. Oferta externa e argumentul cel mai puternic.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
    ],
  },
  {
    id: 23, module: 'Negocierea Salariului', moduleIcon: '💼',
    principle: 'Valoarea ta pe piata e determinata de piata, nu de angajator — Cerceteaza salariile din industrie, documenteaza-ti contributiile si cere o marire bazata pe date obiective, nu pe sentimente.',
    situation: 'Urmeaza evaluarea anuala. Stii ca colegul cu aceleasi responsabilitati castiga cu 600 RON mai mult.',
    character: 'Tu, 27 ani',
    choices: [
      { text: 'Nu spun nimic — e inconfortabil sa vorbesc despre bani', emoji: '🙈', tag: 'Evitare', score: -30, color: '#FF4D4D', consequence: 'Tacerea te costa 600 RON/luna = 7.200 RON/an. Conversatiile incomode despre bani sunt cele mai profitabile.', projection: [0,0,0,0,0,0,0,0] },
      { text: 'Cer marire bazata pe performanta si piata, nu pe colegul meu', emoji: '📊', tag: 'Profesionist', score: 100, color: '#00FF87', consequence: 'Abordarea corecta! Argumentezi cu valoarea adusa si date de piata, nu cu comparatii care pot crea tensiuni.', projection: [0,600,1200,1800,2400,3000,3600,4200] },
      { text: 'Ma plang ca colegul castiga mai mult', emoji: '😤', tag: 'Gresit', score: -40, color: '#FF4D4D', consequence: 'Comparatiile salariale directe creeaza tensiuni si te pozitioneaza prost. Argumenteaza cu valoarea ta, nu cu altii.', projection: [0,-200,-200,-200,-200,-200,-200,-200] },
      { text: 'Imi caut alt job fara sa incerc negocierea', emoji: '🚪', tag: 'Prematur', score: 20, color: '#FFB800', consequence: 'Schimbarea jobului fara sa incerci negocierea e ca si cum ai parasi o masa buna pentru ca nu ai cerut sare.', projection: [0,600,1200,1800,2400,3000,3600,4200] },
    ],
  },
  {
    id: 24, module: 'Negocierea Salariului', moduleIcon: '💼',
    principle: 'Tariful tau de freelancer reflecta valoarea ta — A accepta mai putin decat rata ta de piata trimite un semnal gresit si creeaza un precedent dificil de schimbat. Negocierea e o abilitate, nu o confruntare.',
    situation: 'Un client nou iti ofera 50 RON/ora. Rata ta curenta e 70 RON/ora.',
    character: 'Tu, 26 ani, freelancer',
    choices: [
      { text: 'Accept — am nevoie de proiecte', emoji: '😔', tag: 'Subvalorizare', score: -30, color: '#FF4D4D', consequence: 'Acceptand sub rata ta creezi un precedent. Clientul va pleca sau va cere mai mult la acelasi pret.', projection: [0,-20,-40,-60,-80,-100,-120,-140] },
      { text: 'Refuz ferm si continui cu clientii actuali', emoji: '🚫', tag: 'Principii', score: 70, color: '#FFB800', consequence: 'Corect sa iti aperi tariful, dar un refuz fara negociere pierde un potential client care poate accepta un compromis.', projection: [0,0,0,0,0,0,0,0] },
      { text: 'Negociez la 65 RON/ora si explic valoarea adusa', emoji: '🤝', tag: 'Negociere', score: 100, color: '#00FF87', consequence: 'Perfect! Compromisul cu argumente de valoare e cea mai profesionista abordare. Clientul intelege ce plateste.', projection: [0,650,1300,1950,2600,3250,3900,4550] },
      { text: 'Accept dar ii spun ca voi revizui rata dupa 3 luni', emoji: '⏰', tag: 'Strategic', score: 80, color: '#00C6FF', consequence: 'Strategie acceptabila. Obtii clientul si iti pastrezi planul de a reveni la rata corecta dupa ce demonstrezi valoarea.', projection: [0,500,1000,1500,2100,2700,3300,3900] },
    ],
  },
  {
    id: 25, module: 'Cadouri & Sarbatori', moduleIcon: '🎁',
    principle: 'Sarbatorile nu ar trebui sa creeze datorii — Cheltuielile de Craciun platite pe credit se adauga la stresul financiar al noului an. Un buget fix stabilit in avans e cel mai bun cadou pe care ti-l poti face tie insuti.',
    situation: 'Se apropie Craciunul. Familia se asteapta la cadouri, dar bugetul e strans.',
    character: 'Tu, 25 ani',
    choices: [
      { text: 'Cumpar tot ce trebuie pe credit — e o data pe an', emoji: '💳', tag: 'Credit sezonier', score: -30, color: '#FF4D4D', consequence: 'Craciunul pe credit inseamna ca platesti sarbatoarea si in ianuarie, februarie, martie. Bucuria se termina, datoria ramane.', projection: [0,-500,-1000,-1500,-1000,-500,0,500] },
      { text: 'Stabilesc un buget fix de 500 RON si ma incadrez', emoji: '📊', tag: 'Buget disciplinat', score: 100, color: '#00FF87', consequence: 'Intelept! Cadourile semnificative nu trebuie sa fie scumpe. Un buget clar elimina stresul si vinovatia.', projection: [0,-500,-500,0,200,400,600,800] },
      { text: 'Nu cumpar nimic — explic ca nu am bani', emoji: '🗣️', tag: 'Comunicare', score: 60, color: '#FFB800', consequence: 'Comunicarea onesta e mai valoroasa decat cadourile pe credit. Familia intelege realitatea financiara.', projection: [0,0,200,400,600,800,1000,1200] },
      { text: 'Fac cadouri handmade sau experiente in loc de obiecte', emoji: '🎨', tag: 'Creativ', score: 90, color: '#00C6FF', consequence: 'Excelent! Cadourile personalizate au valoare emotionala mai mare si cost financiar mai mic. Win-win.', projection: [0,-200,-200,100,300,500,700,900] },
    ],
  },
  {
    id: 26, module: 'Cadouri & Sarbatori', moduleIcon: '🎁',
    principle: 'Presiunea sociala e cel mai scump lux — A cheltui mai mult decat iti permiti pentru a respecta asteptarile sociale iti afecteaza finantele reale. Comunicarea onesta costa zero RON.',
    situation: 'Prietenul cel mai bun se casatoreste. Plicul de nunta standard in cercul vostru: 1.500 RON.',
    character: 'Tu, 26 ani',
    choices: [
      { text: 'Dau 1.500 RON chiar daca ma doare', emoji: '😰', tag: 'Presiune sociala', score: 30, color: '#FFB800', consequence: '1.500 RON e o suma mare daca bugetul tau nu o permite. Prietenia adevarata nu se masoara in bani.', projection: [0,-1500,-1000,-500,0,500,1000,1500] },
      { text: 'Discut cu prietenul si explic ca dau cat imi permit', emoji: '🗣️', tag: 'Comunicare onesta', score: 100, color: '#00FF87', consequence: 'Un prieten adevarat intelege. Comunicarea onesta pastreaza atat prietenia cat si sanatatea financiara.', projection: [0,-500,-500,0,200,400,600,800] },
      { text: 'Dau 500 RON si nu imi fac griji', emoji: '💪', tag: 'Asertiv', score: 80, color: '#00C6FF', consequence: 'Dai cat iti permiti fara sa te justifici excesiv. Prezenta ta la eveniment valoreaza mai mult decat suma din plic.', projection: [0,-500,-500,0,200,400,600,800] },
      { text: 'Iau credit ca sa dau suma asteptata', emoji: '💳', tag: 'Credit social', score: -40, color: '#FF4D4D', consequence: 'A te indatora pentru a respecta conventii sociale e una din cele mai costisitoare decizii financiare.', projection: [0,-1500,-2000,-1500,-1000,-500,0,500] },
    ],
  },
  {
    id: 27, module: 'Cadouri & Sarbatori', moduleIcon: '🎁',
    principle: 'FOMO financiar costa bani reali — Teama de a rata o experienta de grup poate duce la decizii financiare proaste. O alternativa mai accesibila sau o amanare planificata e intotdeauna mai buna decat o datorie.',
    situation: 'Colegii propun o vacanta de grup de Revelion — costul per persoana: 2.000 RON. Nu ai bugetul acum.',
    character: 'Tu, 26 ani',
    choices: [
      { text: 'Accept si pun pe card — YOLO, e o data pe an', emoji: '🎉', tag: 'Impuls', score: -30, color: '#FF4D4D', consequence: '2.000 RON pe card la Revelion inseamna ca platesti sarbatoarea si in ianuarie si februarie. Bucuria dureaza 3 zile, datoria 6 luni.', projection: [0,-2000,-1500,-1000,-500,0,500,1000] },
      { text: 'Refuz si organizez ceva mai accesibil cu prietenii apropiati', emoji: '🏡', tag: 'Alternativa', score: 90, color: '#00FF87', consequence: 'Inteligent! Creezi o alternativa placuta la un cost pe care ti-l permiti. Amintirile nu depind de buget.', projection: [0,-200,-200,100,300,500,700,900] },
      { text: 'Cer sa amanam vacanta cu 2 luni ca sa economisesc', emoji: '📅', tag: 'Planificare', score: 100, color: '#00C6FF', consequence: 'Cea mai matura abordare! Participi la experienta de grup fara a te indatora. Propunerea ta poate fi apreciata de toti.', projection: [0,1000,2000,-2000,-1000,0,500,1000] },
      { text: 'Accept si iau bani imprumut', emoji: '🙏', tag: 'Dependenta', score: -20, color: '#FFB800', consequence: 'Imprumuturile pentru experiente de grup creeaza obligatii financiare si emotionale. Nu merita presiunea.', projection: [0,-2000,-1500,-1000,-500,0,500,1000] },
    ],
  },
  {
    id: 28, module: 'Inflatie & Economii', moduleIcon: '📉',
    principle: 'Banii in cont curent pierd valoare real — Cu o inflatie de 6%, 10.000 RON tinuti in cont curent valorează efectiv 9.400 RON dupa un an. Banii care nu lucreaza, muncesc impotriva ta.',
    situation: 'Ai 10.000 RON in cont curent de 2 ani. Inflatia e 6%. Ce faci?',
    character: 'Tu, 26 ani',
    choices: [
      { text: 'Ii las acolo — sunt in siguranta', emoji: '🏦', tag: 'Pierdere reala', score: -30, color: '#FF4D4D', consequence: 'In siguranta nominal, dar cu inflatie de 6% pierzi 600 RON/an in putere de cumparare. Dupa 2 ani ai pierdut echivalentul a 1.200 RON.', projection: [10000,9400,8836,8306,7808,7339,6899,6485] },
      { text: 'Mut in depozit la 5.5% — pierd putin dar e sigur', emoji: '🏛️', tag: 'Partial bun', score: 60, color: '#FFB800', consequence: 'Mai bine decat contul curent, dar tot sub inflatie. Banii isi pastreaza partial valoarea dar nu cresc real.', projection: [10000,10550,11130,11742,12388,13069,13788,14547] },
      { text: 'Investesc 7.000 RON in ETF-uri, 3.000 raman fond de urgenta', emoji: '📈', tag: 'Optim', score: 100, color: '#00FF87', consequence: 'Decizie optima! Fondul de urgenta ramas, restul lucreaza pentru tine. Randament mediu 8-10% bate inflatia consistent.', projection: [10000,10700,11449,12250,13108,14026,15007,16058] },
      { text: 'Cumpar aur — e cel mai sigur in inflatie', emoji: '🥇', tag: 'Mit financiar', score: 20, color: '#FFB800', consequence: 'Aurul e un hedger partial impotriva inflatiei dar volatil si fara randament din dividende. ETF-urile sunt mai eficiente pe termen lung.', projection: [10000,10300,10609,10927,11255,11593,11941,12299] },
    ],
  },
  {
    id: 29, module: 'Inflatie & Economii', moduleIcon: '📉',
    principle: 'Puterea de cumparare e salariul real — Un salariu nominal mai mare cu 5% in conditii de inflatie 8% inseamna de fapt o scadere reala a venitului cu 3%. Negocierea salariului trebuie sa tina cont de inflatie.',
    situation: 'Preturile au crescut cu 8% fata de anul trecut. Salariul tau a crescut cu 5%. Ce faci?',
    character: 'Tu, 27 ani',
    choices: [
      { text: 'Nu fac nimic — e temporar', emoji: '🙄', tag: 'Pasivitate', score: -20, color: '#FF4D4D', consequence: 'Inflatia nu e intotdeauna temporara. In 3 ani de inflatie mai mare decat marirea salariului pierzi semnificativ din puterea de cumparare.', projection: [0,-300,-600,-900,-1200,-1500,-1800,-2100] },
      { text: 'Negociez o marire salariala care sa acopere inflatia', emoji: '💼', tag: 'Proactiv', score: 100, color: '#00FF87', consequence: 'Exact ce trebuie! Salariul real trebuie sa creasca cel putin cu rata inflatiei pentru a-ti mentine stilul de viata.', projection: [0,300,600,900,1200,1500,1800,2100] },
      { text: 'Reduc cheltuielile discretionare cu 10%', emoji: '✂️', tag: 'Adaptare', score: 90, color: '#00C6FF', consequence: 'Masura practica si rapida! Reducerea cheltuielilor neesential compenseaza partial impactul inflatiei.', projection: [0,200,400,600,800,1000,1200,1400] },
      { text: 'Iau un job part-time in plus pentru venituri extra', emoji: '💪', tag: 'Diversificare venit', score: 80, color: '#FFB800', consequence: 'Solutie eficienta pe termen scurt. Atentie la burnout — asigura-te ca venitul extra merita costul energiei investite.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
    ],
  },
  {
    id: 30, module: 'Inflatie & Economii', moduleIcon: '📉',
    principle: 'Dobanda variabila transfera riscul catre tine — Cand alegi dobanda variabila la un credit pe termen lung, iti asumi riscul cresterii ratelor. Refinantarea la dobanda fixa in momentele de crestere e o decizie de protectie, nu de panica.',
    situation: 'Rata la creditul ipotecar a crescut cu 400 RON/luna din cauza dobanzii variabile. Ce faci?',
    character: 'Tu, 28 ani',
    choices: [
      { text: 'Nu fac nimic — sper sa scada', emoji: '🙏', tag: 'Pasivitate', score: -30, color: '#FF4D4D', consequence: 'Ratele pot continua sa creasca. Speranta nu e o strategie financiara. Actioneaza inainte ca situatia sa devina critica.', projection: [0,-400,-800,-1200,-1600,-2000,-2400,-2800] },
      { text: 'Refinantez la dobanda fixa imediat', emoji: '🔒', tag: 'Protectie', score: 100, color: '#00FF87', consequence: 'Decizie inteleapta! Blochezi rata la un nivel previzibil si elimini riscul unor cresteri viitoare. Costul refinantarii merita siguranta.', projection: [0,-400,-400,-400,-400,-400,-400,-400] },
      { text: 'Reduc alte cheltuieli pentru a acoperi diferenta', emoji: '✂️', tag: 'Adaptare', score: 80, color: '#00C6FF', consequence: 'Solutie buna pe termen scurt. Combina-o cu analiza refinantarii pentru o solutie pe termen lung.', projection: [0,-400,-400,-400,-300,-200,-100,0] },
      { text: 'Vand apartamentul — nu mai pot face fata', emoji: '🏚️', tag: 'Radical', score: -20, color: '#FFB800', consequence: 'Decizie extrema pentru o crestere de 400 RON. Exploreaza mai intai refinantarea, restructurarea creditului sau reducerea cheltuielilor.', projection: [0,-400,-400,5000,5000,5000,5000,5000] },
    ],
  },
  {
    id: 31, module: 'Prima Vacanta', moduleIcon: '🌍',
    principle: 'Vacanta planificata costa jumatate fata de cea impulsiva — Rezervarile facute cu 3-6 luni inainte pot fi cu 40-60% mai ieftine. Economisitul lunar pentru vacanta elimina nevoia creditului si stresul asociat.',
    situation: 'Vrei prima vacanta in strainatate — costul estimat: 3.000 RON.',
    character: 'Tu, 23 ani, primul an de job',
    choices: [
      { text: 'Pun pe card si platesc in rate', emoji: '💳', tag: 'Credit vacanta', score: -30, color: '#FF4D4D', consequence: 'Vacanta pe credit inseamna ca platesti relaxarea si dupa ce te-ai intors. Stresul datoriei anuleaza beneficiile vacantei.', projection: [0,-3000,-2500,-2000,-1500,-1000,-500,0] },
      { text: 'Economisesc 500 RON/luna timp de 6 luni', emoji: '📅', tag: 'Planificare', score: 100, color: '#00FF87', consequence: 'Perfect! Vacanta platita integral inainte = relaxare totala. 6 luni de asteptare pentru o experienta fara datorii.', projection: [0,500,1000,1500,2000,2500,-500,500] },
      { text: 'Iau din fondul de urgenta — merita', emoji: '🛡️', tag: 'Risc fond urgenta', score: -40, color: '#FF4D4D', consequence: 'Fondul de urgenta nu e pentru vacante. Il golesti azi, maine apare o urgenta reala si esti nepregatit.', projection: [0,-3000,-2500,-2000,-1500,-1000,-500,0] },
      { text: 'Aleg o destinatie mai accesibila in buget actual', emoji: '🗺️', tag: 'Adaptare', score: 90, color: '#00C6FF', consequence: 'Inteligent! O vacanta accesibila acum + economii pentru una mai mare mai tarziu. Nu trebuie sa alegi intre vacanta si sanatatea financiara.', projection: [0,-1000,-500,0,500,1000,1500,2000] },
    ],
  },
  {
    id: 32, module: 'Prima Vacanta', moduleIcon: '🌍',
    principle: 'Bugetul e o limita, nu o sugestie — Depasirea bugetului de vacanta cu 1.000 RON pe card inseamna ca platesti vacanta si dupa ce te-ai intors acasa. Alternativele in buget exista intotdeauna.',
    situation: 'Ai buget de 2.500 RON pentru vacanta. Agentia iti ofera all-inclusive cu 3.500 RON.',
    character: 'Tu, 25 ani',
    choices: [
      { text: 'Accept si platesc diferenta pe card', emoji: '💳', tag: 'Depasire buget', score: -30, color: '#FF4D4D', consequence: '1.000 RON in plus pe card pentru vacanta = 1-2 luni de stres financiar dupa. Bugetul exista pentru un motiv.', projection: [0,-3500,-3000,-2500,-2000,-1500,-1000,-500] },
      { text: 'Refuz si caut pachete in bugetul meu', emoji: '🔍', tag: 'Disciplina', score: 100, color: '#00FF87', consequence: 'Corect! Exista intotdeauna alternative in buget. Disciplina financiara in vacanta e la fel de importanta ca in orice alta situatie.', projection: [0,-2500,-2000,-1500,-1000,-500,0,500] },
      { text: 'Negociez cu agentia sau caut early booking', emoji: '🤝', tag: 'Strategic', score: 90, color: '#00C6FF', consequence: 'Excelent! Negocierea sau cautarea de oferte mai bune poate aduce pachetul dorit la pretul potrivit.', projection: [0,-2500,-2000,-1500,-1000,-500,0,500] },
      { text: 'Renunt la vacanta — nu am suficient', emoji: '😔', tag: 'Prea restrictiv', score: 20, color: '#FFB800', consequence: 'Nu trebuie sa renunti complet. Exista optiuni in bugetul tau. Cauta alternative inainte sa renunti.', projection: [0,0,500,1000,1500,2000,2500,3000] },
    ],
  },
  {
    id: 33, module: 'Prima Vacanta', moduleIcon: '🌍',
    principle: 'Presiunea grupului poate fi cea mai scumpa destinatie — A cheltui mai mult decat iti permiti pentru a fi in acord cu grupul iti afecteaza finantele, nu vacanta. Comunicarea asertiva e o abilitate financiara.',
    situation: 'Prietenul vrea un hotel mai scump cu 800 RON in plus per persoana. Ce faci?',
    character: 'Tu, 26 ani',
    choices: [
      { text: 'Platesc in plus ca sa nu stric atmosfera', emoji: '😰', tag: 'Presiune sociala', score: -20, color: '#FF4D4D', consequence: '800 RON in plus pentru un pat mai bun nu imbunatateste vacanta proportional. Atmosfera buna vine din companie, nu din hotel.', projection: [0,-800,-300,200,700,1200,1700,2200] },
      { text: 'Discut si propun un compromis — hotel mediu', emoji: '🤝', tag: 'Comunicare', score: 100, color: '#00FF87', consequence: 'Comunicarea deschisa gaseste solutii pe care toata lumea le accepta. Un prieten bun va intelege.', projection: [0,-400,100,600,1100,1600,2100,2600] },
      { text: 'Merg la hotelul meu planificat, ei la al lor', emoji: '💪', tag: 'Asertiv', score: 90, color: '#00C6FF', consequence: 'Asertivitate financiara sanatoasa! Fiecare alege in limita bugetului sau. Va petreceti ziua impreuna oricum.', projection: [0,0,500,1000,1500,2000,2500,3000] },
      { text: 'Renunt la vacanta', emoji: '😔', tag: 'Evitare', score: -30, color: '#FFB800', consequence: 'Renuntarea e mai putin eficienta decat comunicarea. Propune un compromis inainte sa renunti.', projection: [0,0,500,1000,1500,2000,2500,3000] },
    ],
  },
  {
    id: 34, module: 'Planificarea Familiei', moduleIcon: '👶',
    principle: 'Un copil costa in medie 2.000-3.000 RON/luna in primul an — Scutece, medicamente, ingrijire, echipament — costurile sunt reale si predictibile. Planificarea financiara cu 1-2 ani inainte face diferenta dintre stres si bucurie.',
    situation: 'Voi vreti un copil in 2 ani. Nu ati inceput sa va pregatiti financiar.',
    character: 'Tu, 28 ani, in cuplu',
    choices: [
      { text: 'Nu ne pregatim — vom vedea cand vine momentul', emoji: '🤷', tag: 'Nepregatit', score: -30, color: '#FF4D4D', consequence: 'Un copil aduce bucurie si costuri reale. Fara pregatire financiara, primul an poate deveni o sursa majora de stres.', projection: [0,0,0,-2000,-3000,-3000,-3000,-3000] },
      { text: 'Calculam costurile reale si stabilim un plan de economii', emoji: '📊', tag: 'Planificare', score: 100, color: '#00FF87', consequence: 'Exact ce trebuie! 2 ani e timp suficient pentru a construi un fond solid si a reduce stresul financiar din primul an.', projection: [0,1000,2000,3000,4000,1000,2000,3000] },
      { text: 'Cumparam tot ce ne trebuie din timp', emoji: '🛍️', tag: 'Cheltuieli premature', score: -10, color: '#FFB800', consequence: 'Multe achizitii pentru bebelus se fac mai bine dupa nastere, cand stii exact ce ai nevoie. Evita cheltuielile premature.', projection: [0,-2000,-1500,-1000,0,500,1000,1500] },
      { text: 'Cream fondul de urgenta la 6 salarii inainte', emoji: '🛡️', tag: 'Prudent', score: 90, color: '#00C6FF', consequence: 'Intelept! Un fond de urgenta solid e fundamentul cel mai important inainte de a deveni parinti.', projection: [0,1500,3000,4500,6000,3000,4000,5000] },
    ],
  },
  {
    id: 35, module: 'Planificarea Familiei', moduleIcon: '👶',
    principle: 'Concediul parental reduce venitul familiei cu 20-40% — Fondul de urgenta extins la 6 luni de cheltuieli e esential inainte de a deveni parinti. Aceasta perioada e predictibila — pregatirea nu e optionala.',
    situation: 'Concediu de maternitate/paternitate reduce venitul familiei cu 40%. Ce faci?',
    character: 'Tu, 29 ani, proaspat parinte',
    choices: [
      { text: 'Nu facusem niciun plan — improvizam', emoji: '😰', tag: 'Criza', score: -40, color: '#FF4D4D', consequence: 'Improvizarea in aceasta perioada creeaza stres financiar maxim intr-un moment deja solicitant emotional. Planificarea era esentiala.', projection: [0,-2000,-4000,-6000,-4000,-2000,0,2000] },
      { text: 'Avem fond de urgenta de 6 luni — ne descurcam', emoji: '🛡️', tag: 'Pregatit', score: 100, color: '#00FF87', consequence: 'Perfect pregatiti! Fondul de urgenta face aceasta tranzitie lina si fara stres financiar. Exact pentru asta a fost construit.', projection: [0,-2000,-4000,-6000,-4000,-2000,0,2000] },
      { text: 'Reducem toate cheltuielile discretionare', emoji: '✂️', tag: 'Adaptare', score: 80, color: '#00C6FF', consequence: 'Masura practica! Combinata cu un fond partial, reducerea cheltuielilor ajuta sa traversezi aceasta perioada.', projection: [0,-1000,-2000,-3000,-2000,-1000,0,1000] },
      { text: 'Luam credit pentru a acoperi diferenta', emoji: '💳', tag: 'Credit necesar', score: -20, color: '#FFB800', consequence: 'Creditul intr-o perioada de venit redus creeaza o spirala dificila. Pregatirea anticipata elimina aceasta nevoie.', projection: [0,-2500,-5000,-7500,-5000,-2500,0,2500] },
    ],
  },
  {
    id: 36, module: 'Planificarea Familiei', moduleIcon: '👶',
    principle: 'Dobanda compusa lucreaza cel mai bine pentru copii — 300 RON/luna investiti de la nasterea copilului pot deveni 150.000-200.000 RON pana la 18 ani (la 7% randament anual). Timpul e cel mai mare avantaj al unui copil.',
    situation: 'Vrei sa deschizi un cont de economii pentru copilul tau care s-a nascut. Cat pui lunar?',
    character: 'Tu, 27 ani',
    choices: [
      { text: 'Nimic — mai am timp sa ma gandesc', emoji: '⏰', tag: 'Amanare', score: -30, color: '#FF4D4D', consequence: 'Fiecare luna amanata inseamna mai putina dobanda compusa. La 7% randament, 100 RON pusi azi valoreaza dublu fata de aceiasi 100 RON pusi peste 10 ani.', projection: [0,0,0,0,0,0,0,0] },
      { text: '100 RON/luna — mic dar constant', emoji: '✅', tag: 'Start mic', score: 80, color: '#00FF87', consequence: 'Excelent start! 100 RON/luna timp de 18 ani la 7% randament = aproximativ 45.000 RON. Constanta bate marimea.', projection: [100,214,335,462,596,738,887,1045] },
      { text: '300 RON/luna intr-un ETF pe termen lung', emoji: '📈', tag: 'Optim', score: 100, color: '#00C6FF', consequence: 'Decizie optima! 300 RON/luna timp de 18 ani la 7% randament = aproximativ 135.000 RON. Un start de viata extraordinar pentru copilul tau.', projection: [300,642,1005,1386,1787,2208,2651,3116] },
      { text: 'Astept sa am mai multi bani si pun mai mult', emoji: '⏳', tag: 'Procrastinare', score: -20, color: '#FFB800', consequence: "'Mai multi bani' nu vin singuri. Incepand cu 100 RON azi e infinit mai bun decat 1.000 RON incepand peste 5 ani.", projection: [0,0,0,0,0,1000,2100,3307] },
    ],
  },
  {
    id: 37, module: 'Achizitia unui Vehicul', moduleIcon: '🚗',
    principle: 'Masina noua e cel mai scump depreciabil — O masina noua pierde 15-20% din valoare in momentul in care iese din showroom. Second-hand inseamna ca altcineva a platit aceasta depreciere in locul tau.',
    situation: 'Vrei prima masina. Ai economii de 20.000 RON. Gasesti o masina second-hand fiabila la 12.000 RON sau una noua la 75.000 RON pe credit.',
    character: 'Tu, 24 ani',
    choices: [
      { text: 'Masina noua pe credit 5 ani — merit prima masina noua', emoji: '🚙', tag: 'Status symbol', score: -20, color: '#FF4D4D', consequence: 'O masina de 75.000 RON pe credit 5 ani inseamna rate de ~1.500 RON/luna + asigurare. Iar masina pierde 15.000 RON valoare in primul an.', projection: [0,-1500,-3000,-4500,-6000,-7500,-9000,-10500] },
      { text: 'Masina second-hand — raman cu 8.000 RON economii', emoji: '🔧', tag: 'Echilibrat', score: 90, color: '#00FF87', consequence: 'Inteligent! Platesti cash, nu ai rate si pastrezi 8.000 RON economii. Altcineva a platit deprecierea initiala in locul tau.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
      { text: 'Astept 6 luni, economisesc si cumpar second-hand cash', emoji: '⏳', tag: 'Rabdare', score: 100, color: '#00FF87', consequence: 'Decizie maxima! In 6 luni ai mai multi bani, poti cauta mai bine si cumperi exact ce vrei fara presiune.', projection: [0,1000,2000,3000,4000,-8000,-7000,-6000] },
      { text: 'Cumpar masina noua cash din economii — le epuizez complet', emoji: '💸', tag: 'Risc fond urgenta', score: -40, color: '#FF4D4D', consequence: 'Nu ai suficient pentru masina noua si ai epuiza complet economiile. Ramai fara fond de urgenta si fara posibilitatea de a face fata oricarei urgente.', projection: [0,-20000,-19000,-18000,-17000,-16000,-15000,-14000] },
    ],
  },
  {
    id: 38, module: 'Achizitia unui Vehicul', moduleIcon: '🚗',
    principle: 'Upgrade-ul vehiculului trebuie planificat, nu impulsionat — Schimbarea masinii doar pentru ca vrei ceva mai bun, fara calcul financiar, poate insemna ani de rate pentru un activ care pierde valoare constant.',
    situation: 'Ai masina si vrei sa o schimbi cu una mai buna. Masina actuala valoreaza 20.000 RON. Cea noua costa 80.000 RON.',
    character: 'Tu, 27 ani',
    choices: [
      { text: 'Vand masina actuala si iau credit pentru diferenta de 60.000 RON', emoji: '💳', tag: 'Credit calculat', score: 80, color: '#FFB800', consequence: 'Acceptabil daca ratele sunt sub 20% din venit. Calculeaza costul total al creditului inainte de a semna.', projection: [0,-1200,-2400,-3600,-2400,-1200,0,1200] },
      { text: 'Iau credit pentru toata suma, pastrez masina veche', emoji: '🚗', tag: 'Supraindatorare', score: -40, color: '#FF4D4D', consequence: 'Doua masini + credit de 80.000 RON e o povara financiara majora. Masina veche pierde valoare in timp ce platesti credit pentru cea noua.', projection: [0,-1600,-3200,-4800,-6400,-8000,-9600,-11200] },
      { text: 'Vand masina si cumpar alta second-hand de 20.000 RON cash', emoji: '♻️', tag: 'Zero datorii', score: 100, color: '#00FF87', consequence: 'Decizie financiara perfecta! Zero rate, zero dobanzi. Diferenta de valoare ramane in buzunarul tau, nu al bancii.', projection: [0,500,1000,1500,2000,2500,3000,3500] },
      { text: 'Astept sa economisesc diferenta si platesc integral', emoji: '⏳', tag: 'Rabdare', score: 90, color: '#00C6FF', consequence: 'Excelent! Fara credit inseamna fara dobanzi. 60.000 RON economisiti iti cumpara exact ce vrei fara costuri ascunse.', projection: [0,1000,2000,3000,4000,5000,-55000,-54000] },
    ],
  },
  {
    id: 39, module: 'Achizitia unui Vehicul', moduleIcon: '🏍️',
    principle: 'Fondul de urgenta e sacru — Indiferent cat de tentanta e o achizitie, fondul de urgenta nu se atinge pentru bunuri discretionare. Economiile separate exista exact pentru astfel de dorinte planificate.',
    situation: 'Vrei o motocicleta de 20.000 RON pentru distractie. Ai un fond de urgenta de 6.000 RON si economii separate de 5.000 RON.',
    character: 'Tu, 25 ani',
    choices: [
      { text: 'Cumpar din fondul de urgenta — nu am suficient oricum', emoji: '🛡️', tag: 'Risc fond urgenta', score: -40, color: '#FF4D4D', consequence: 'Fondul de urgenta exista pentru urgente, nu pentru achizitii dorite. Golind-ul ramai expus la orice surpriza financiara.', projection: [0,-6000,-5000,-4000,-3000,-2000,-1000,0] },
      { text: 'Economisesc diferenta de 15.000 RON si cumpar fara sa ating fondurile', emoji: '📅', tag: 'Disciplina', score: 100, color: '#00FF87', consequence: 'Decizie financiara matura! Pastrezi fondul de urgenta intact si cumperi exact ce vrei fara datorii sau riscuri.', projection: [0,1000,2000,3000,4000,5000,-15000,-14000] },
      { text: 'Iau credit rapid — nu vreau sa ating economiile', emoji: '⚡', tag: 'Credit inutil', score: -30, color: '#FF4D4D', consequence: 'Credit pentru o achizitie discretionara cand ai economii e costisitor si inutil. Costul dobanzii e o pierdere pura.', projection: [0,-500,-1000,-1500,-2000,-1500,-1000,-500] },
      { text: 'Astept sa economisesc suma fara sa ating fondurile existente', emoji: '⏳', tag: 'Rabdare', score: 90, color: '#00C6FF', consequence: 'Excelent! Pacienta financiara e o virtute. Motocicleta cumparata din economii proprii aduce satisfactie dubla.', projection: [0,1000,2000,3000,4000,5000,-15000,-14000] },
    ],
  },
]

export const CHALLENGES = [
  { id: 1, icon: '🍕', title: 'Zero livrari, 7 zile', desc: 'Nu comanda mancare sau bauturi 7 zile consecutive. Gatesti sau cumperi de la supermarket.', saving: '~150-300 RON', tip: 'Media unui tanar cheltuie 200-400 RON/luna pe livrari. E prima economie automata.' },
  { id: 2, icon: '✂️', title: 'Audit abonamente', desc: 'Listeaza TOATE abonamentele lunare si anuleaza cel putin unul neutilizat.', saving: '~30-150 RON/luna', tip: 'Romanii au in medie 4-6 abonamente active. Jumatate sunt subutilizate.' },
  { id: 3, icon: '💰', title: 'Regula 24 ore', desc: 'Inainte de orice cumparatura mai mare de 200 RON, astepti 24 de ore fara exceptie.', saving: '~200-800 RON', tip: '80% din cumpararaturile impulsive nu se mai fac dupa 24h de reflectie.' },
  { id: 4, icon: '📊', title: 'Tracker 30 zile', desc: 'Noteaza FIECARE cheltuiala 30 de zile intr-o aplicatie sau caiet.', saving: '~15-20% cheltuieli', tip: 'Simpla urmarire a cheltuielilor le reduce in medie cu 15-20%.' },
  { id: 5, icon: '🎓', title: '1 ora de educatie financiara', desc: 'Citeste sau asculta 1 ora de continut despre finante personale aceasta saptamana.', saving: 'Mii de RON pe termen lung', tip: "Recomandare: 'Omul cel mai bogat din Babilon' — lectura dureaza 3-4 ore." },
  { id: 6, icon: '🏦', title: 'Automatizeaza economiile', desc: 'Seteaza un transfer automat de 10% din salariu in ziua in care primesti banii.', saving: '10% din venit', tip: 'Plateste-te pe tine primul. Nu economisi ce ramane — cheltuiesti ce ramane dupa ce ai economisit.' },
  { id: 7, icon: '🔍', title: 'Calculeaza rata de economisire', desc: 'Calculeaza exact cate procente din venit net economisesti acum.', saving: 'Constiintizare', tip: 'Rata optima: 15-20% din venit net. Sub 10% e zona de risc.' },
  { id: 8, icon: '🚫', title: 'Digital detox shopping', desc: 'Goleste cosul din toate magazinele online si nu adauga nimic 5 zile.', saving: '~100-500 RON', tip: 'Elimina notificarile push de la aplicatiile de shopping pentru a reduce tentatiile permanent.' },
]
